// Seed script for George's favorite wines from MEMORY.md

const wines = [
  {
    id: '1',
    name: 'Napa Valley Cabernet Sauvignon',
    producer: 'Louis M. Martini',
    vintage: '2021',
    region: 'Napa Valley',
    country: 'USA',
    grapes: ['Cabernet Sauvignon'],
    type: 'red',
    style: 'Bold & Full-bodied',
    priceRange: '$25-35',
    foodPairings: ['Grilled steak', 'Aged cheese', 'Roasted lamb'],
    wineryDescription: 'Historic Napa Valley winery known for elegant, structured Cabernets.',
    rating: 5,
    liked: true,
    tastingNotes: 'Structured, bold tannins, perfect balance. One of my absolute favorites.',
    location: 'Home',
    dateTasted: '2024-01-15',
    createdAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: '2',
    name: 'Cabernet Sauvignon',
    producer: 'JAX Vineyards',
    vintage: '2020',
    region: 'Napa Valley',
    country: 'USA',
    grapes: ['Cabernet Sauvignon'],
    type: 'red',
    style: 'Powerful & Complex',
    priceRange: '$40-60',
    foodPairings: ['Prime rib', 'Wild game', 'Dark chocolate'],
    wineryDescription: 'Premium Napa producer crafting bold, age-worthy Cabernets.',
    rating: 5,
    liked: true,
    tastingNotes: 'Exceptional structure, rich dark fruit, perfectly balanced tannins.',
    location: 'Wine tasting',
    dateTasted: '2024-02-10',
    createdAt: new Date('2024-02-10').toISOString(),
  },
  {
    id: '3',
    name: 'St. Giorgio Toscana',
    producer: 'St. Giorgio',
    vintage: '2019',
    region: 'Tuscany',
    country: 'Italy',
    grapes: ['Sangiovese', 'Cabernet Sauvignon', 'Merlot'],
    type: 'red',
    style: 'Super Tuscan - Bold & Elegant',
    priceRange: '$30-45',
    foodPairings: ['Tuscan steak', 'Pasta with ragu', 'Pecorino cheese'],
    wineryDescription: 'Super Tuscan blend combining traditional Sangiovese with international varietals.',
    rating: 5,
    liked: true,
    tastingNotes: 'Complex Super Tuscan, amazing depth and sophistication. Love this style.',
    location: 'Restaurant',
    dateTasted: '2024-03-05',
    createdAt: new Date('2024-03-05').toISOString(),
  },
  {
    id: '4',
    name: 'Cabernet Sauvignon Y3',
    producer: 'Y3 Winery',
    vintage: '2019',
    region: 'Napa Valley',
    country: 'USA',
    grapes: ['Cabernet Sauvignon'],
    type: 'red',
    style: 'Rich & Structured',
    priceRange: '$35-50',
    foodPairings: ['Ribeye steak', 'Braised short ribs', 'Aged cheddar'],
    wineryDescription: 'Boutique Napa producer focusing on premium mountain Cabernets.',
    rating: 4,
    liked: true,
    tastingNotes: 'Excellent Napa Cab with good structure and aging potential.',
    location: 'Home',
    dateTasted: '2024-04-12',
    createdAt: new Date('2024-04-12').toISOString(),
  },
  {
    id: '5',
    name: 'Unánime Gran Vino Tinto',
    producer: 'Unánime',
    vintage: '2018',
    region: 'Rioja',
    country: 'Spain',
    grapes: ['Tempranillo', 'Garnacha'],
    type: 'red',
    style: 'Traditional Rioja - Elegant & Earthy',
    priceRange: '$20-30',
    foodPairings: ['Chorizo', 'Paella', 'Manchego cheese'],
    wineryDescription: 'Classic Rioja producer known for elegant, terroir-driven wines.',
    rating: 4,
    liked: true,
    tastingNotes: 'Great Rioja character, earthy notes, good complexity for the price.',
    location: 'Wine bar',
    dateTasted: '2024-05-20',
    createdAt: new Date('2024-05-20').toISOString(),
  },
  {
    id: '6',
    name: 'Mucchietto Primitivo',
    producer: 'Pasqua',
    vintage: '2020',
    region: 'Puglia',
    country: 'Italy',
    grapes: ['Primitivo'],
    type: 'red',
    style: 'Bold & Fruity',
    priceRange: '$15-25',
    foodPairings: ['BBQ ribs', 'Pizza', 'Spicy sausage'],
    wineryDescription: 'Italian producer specializing in robust, fruit-forward Primitivo.',
    rating: 4,
    liked: false,
    tastingNotes: 'Rich, jammy fruit, very approachable. Great value Italian red.',
    location: 'Home',
    dateTasted: '2024-06-08',
    createdAt: new Date('2024-06-08').toISOString(),
  },
];

console.log(JSON.stringify(wines, null, 2));
